# Generated by Django 5.1.2 on 2024-11-06 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inputTable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputtable',
            name='id_record',
        ),
    ]
