# Generated by Django 5.1.2 on 2024-11-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('id_record', models.IntegerField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(max_length=50)),
            ],
        ),
    ]
