# Generated by Django 5.1.2 on 2024-11-06 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputTable', '0002_remove_inputtable_id_record'),
        ('outputTable', '0002_remove_outputtable_id_record'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='id_tabeleEntrada',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='inputTable.inputtable'),
        ),
        migrations.AddField(
            model_name='record',
            name='id_tabeleSaida',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='outputTable.outputtable'),
        ),
    ]
